apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: rent-a-ride-imageupdater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: rent-a-ride
      useAnnotations: true
