apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: rent-a-ride
  name: mongodb-claim

spec:
  accessModes:
    - ReadWriteOnce

  volumeMode: Filesystem

  resources:
    requests:
      storage: 1Gi

  storageClassName: standard
