apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  ACCESS_TOKEN: {{ .Values.secrets.accessToken | b64enc }}
  REFRESH_TOKEN: {{ .Values.secrets.refreshToken | b64enc }}
