name: Task07

on:
 push:
   branches:
     - feature/task07

jobs:
 tests:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Check Code
      run: ls
    - name: Say Hello
      run: echo "GitHub Actions is working!"
    - name: Check Docker
      run: docker --version
    - name: Build Frontend Image
      run: docker build -t rent-a-ride-frontend:test -f client/Dockerfile .
    
